// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  link: dynamic(() => import("./Link")),
  perguntas: dynamic(() => import("./Perguntas")),
  section: dynamic(() => import("./Section")),
  service: dynamic(() => import("./Service")),
  sobre_nos: dynamic(() => import("./SobreNos")),
  welcome: dynamic(() => import("./Welcome")),
};
